#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"

find_repo_root() {
  local dir="$SCRIPT_DIR"
  while [[ "$dir" != "/" ]]; do
    if [[ -d "$dir/.git" && -f "$dir/index.html" && -f "$dir/visual_archive_editor.html" ]]; then
      printf '%s\n' "$dir"
      return 0
    fi
    dir="$(dirname "$dir")"
  done
  return 1
}

ROOT="$(find_repo_root || true)"

if [[ -z "$ROOT" ]]; then
  echo "ERROR: no encuentro la raíz del repositorio."
  echo "Pon este launcher dentro del repo o dentro de tools/."
  read -r -p "Pulsa Enter para cerrar…"
  exit 1
fi

cd "$ROOT"

# Rebuild the browser-readable media catalogue from the real archive folders.
# The generated file can be committed together with newly added media so the
# online editor sees exactly the same library as the local editor.
python3 - "$ROOT" <<'PY'
import json
import re
import sys
from pathlib import Path

root = Path(sys.argv[1])
media_roots = [
    # Every publishable image folder, including future sections.
    (root / "img", None, False),
    # Local fallback: only use an original when its published source copy
    # does not exist yet.
    (root / "img_originales" / "source", "source", True),
]
manifest = root / "archive_media_manifest.js"
image_ext = {".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif"}
video_ext = {".mp4", ".webm", ".mov", ".m4v"}

previous = {}
if manifest.exists():
    text = manifest.read_text(encoding="utf-8")
    match = re.search(r"window\.ARCHIVE_MEDIA\s*=\s*(\[[\s\S]*\])\s*;?", text)
    if match:
        try:
            previous = {
                item.get("src"): item
                for item in json.loads(match.group(1))
                if isinstance(item, dict) and item.get("src")
            }
        except json.JSONDecodeError:
            previous = {}

entries = []
for media_root, default_project, originals_fallback in media_roots:
    if not media_root.exists():
        continue

    for path in sorted(media_root.rglob("*"), key=lambda p: str(p).lower()):
        if not path.is_file() or path.name.startswith("."):
            continue
        suffix = path.suffix.lower()
        if suffix not in image_ext | video_ext:
            continue

        if originals_fallback:
            relative_original = path.relative_to(media_root)
            if (root / "img" / "source" / relative_original).exists():
                continue

        src = path.relative_to(root).as_posix()
        parts = [part.lower() for part in path.relative_to(root).parts]
        entry = dict(previous.get(src, {}))
        entry["src"] = src
        entry["type"] = "video" if suffix in video_ext else "image"
        is_source = default_project == "source" or (
            len(parts) > 1 and parts[0] == "img" and parts[1] == "source"
        )
        if is_source:
            entry["project"] = "source"

        if any("cutout" in part for part in parts):
            entry["kind"] = "cutout"
        elif entry.get("kind") == "cutout":
            entry.pop("kind", None)

        if is_source:
            entry["project"] = "source"
        elif default_project:
            pass
        elif "collage" in parts:
            entry["project"] = "escitalopram"
        elif "photography" in parts:
            index = parts.index("photography")
            if index + 1 < len(parts) - 1:
                entry["project"] = parts[index + 1]
        elif "super8" in parts:
            entry.setdefault("project", "video")

        entries.append(entry)

manifest.write_text(
    "/* Auto-generated by launch_local_web.command. */\n"
    "window.ARCHIVE_MEDIA = "
    + json.dumps(entries, ensure_ascii=False, indent=2)
    + ";\n",
    encoding="utf-8",
)
print(f"Media library updated: {len(entries)} files")
PY

PORT=8765

# Verify any existing server actually serves THIS repo.
PROBE=".visual_archive_probe"
TOKEN="probe-$$-$(date +%s)-$RANDOM"
printf '%s' "$TOKEN" > "$ROOT/$PROBE"

cleanup() { rm -f "$ROOT/$PROBE" 2>/dev/null || true; }
trap cleanup EXIT

same_repo() {
  local port="$1"
  local got
  got="$(curl -fs "http://localhost:$port/$PROBE?v=$(date +%s)" 2>/dev/null || true)"
  [[ "$got" == "$TOKEN" ]]
}

if lsof -ti tcp:$PORT >/dev/null 2>&1; then
  if same_repo "$PORT"; then
    open "http://localhost:$PORT/visual_archive_editor.html?fresh=$(date +%s)"
    exit 0
  fi

  echo "Puerto 8765 pertenece a otro servidor. Uso 8766."
  PORT=8766

  if lsof -ti tcp:$PORT >/dev/null 2>&1; then
    if same_repo "$PORT"; then
      open "http://localhost:$PORT/visual_archive_editor.html?fresh=$(date +%s)"
      exit 0
    fi
    echo "ERROR: 8765 y 8766 están ocupados por otros servidores."
    read -r -p "Pulsa Enter para cerrar…"
    exit 1
  fi
fi

URL="http://localhost:$PORT/visual_archive_editor.html?fresh=$(date +%s)"

echo
echo "=== VISUAL ARCHIVE LOCAL ==="
echo "Repo: $ROOT"
echo "URL:  $URL"
echo
echo "El editor abre primero el layout guardado en /layouts/."
echo "Pulsa [ continue draft ] si quieres recuperar un borrador local."
echo "Pulsa [ empty + choose ] para vaciar el collage y abrir la biblioteca."
echo
echo "Photo usa:        layouts/visual_archive_layout_photo.js"
echo "Video usa:        layouts/visual_archive_layout_video.js"
echo "Escitalopram usa: layouts/visual_archive_layout_escitalopram.js"
echo "Main usa:         layouts/visual_archive_layout.js"
echo
echo "Deja esta ventana abierta. Ctrl+C para detener."
echo

(
  sleep 1
  open "$URL"
) &

python3 -m http.server "$PORT" --directory "$ROOT"
