/* Auto-generated by Publicar_Imagenes_Web.command. Do not edit by hand. */
window.SOURCE_MEDIA = [
  {
    "src": "img/source/24Sorrodiles#1.jpg",
    "title": "24Sorrodiles#1",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura de pantalla 2020-04-24 a las 11.55.43.png",
    "title": "Captura de pantalla 2020 04 24 a las 11.55.43",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura de pantalla 2020-04-24 a las 11.56.12.png",
    "title": "Captura de pantalla 2020 04 24 a las 11.56.12",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura de pantalla 2021-01-17 a las 20.31.50.png",
    "title": "Captura de pantalla 2021 01 17 a las 20.31.50",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura de pantalla 2021-01-17 a las 20.44.03.png",
    "title": "Captura de pantalla 2021 01 17 a las 20.44.03",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Jacqueline-Jong-Portrait-1960s.jpeg",
    "title": "Jacqueline Jong Portrait 1960s",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/burninglights.jpeg",
    "title": "burninglights",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/collage.jpg",
    "title": "collage",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/petit_silence.jpeg",
    "title": "petit silence",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/taipeistory.jpg",
    "title": "taipeistory",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/wendy-carlos.jpeg",
    "title": "wendy carlos",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/wildatheart.jpg",
    "title": "wildatheart",
    "description": "",
    "href": ""
  }
];
