/* Auto-generated by Preparar_y_Publicar_Web.command. Do not edit by hand. */
window.SOURCE_MEDIA = [
  {
    "src": "img/source/1020878_w445_1500.jpeg",
    "type": "image",
    "title": "1020878 w445 1500",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/1020878_w445_1500.jpeg.web.jpg",
    "type": "image",
    "title": "1020878 w445 1500.jpeg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/24Sorrodiles%231.jpg",
    "type": "image",
    "title": "24Sorrodiles#1",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/24Sorrodiles%231.jpg.web.jpg",
    "type": "image",
    "title": "24Sorrodiles#1.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202020-04-24%20a%20las%2011.55.43.png",
    "type": "image",
    "title": "Captura de pantalla 2020 04 24 a las 11.55.43",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202020-04-24%20a%20las%2011.55.43.png.web.jpg",
    "type": "image",
    "title": "Captura de pantalla 2020 04 24 a las 11.55.43.png.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202020-04-24%20a%20las%2011.56.12.png",
    "type": "image",
    "title": "Captura de pantalla 2020 04 24 a las 11.56.12",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202020-04-24%20a%20las%2011.56.12.png.web.jpg",
    "type": "image",
    "title": "Captura de pantalla 2020 04 24 a las 11.56.12.png.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202021-01-17%20a%20las%2020.31.50.png",
    "type": "image",
    "title": "Captura de pantalla 2021 01 17 a las 20.31.50",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202021-01-17%20a%20las%2020.31.50.png.web.jpg",
    "type": "image",
    "title": "Captura de pantalla 2021 01 17 a las 20.31.50.png.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202021-01-17%20a%20las%2020.44.03.png",
    "type": "image",
    "title": "Captura de pantalla 2021 01 17 a las 20.44.03",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Captura%20de%20pantalla%202021-01-17%20a%20las%2020.44.03.png.web.jpg",
    "type": "image",
    "title": "Captura de pantalla 2021 01 17 a las 20.44.03.png.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Henry_Rox2.jpg",
    "type": "image",
    "title": "Henry Rox2",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Henry_Rox2.jpg.web.jpg",
    "type": "image",
    "title": "Henry Rox2.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Jacqueline-Jong-Portrait-1960s.jpeg",
    "type": "image",
    "title": "Jacqueline Jong Portrait 1960s",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Jacqueline-Jong-Portrait-1960s.jpeg.web.jpg",
    "type": "image",
    "title": "Jacqueline Jong Portrait 1960s.jpeg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Vilem_Flusser_1940.jpg",
    "type": "image",
    "title": "Vilem Flusser 1940",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/Vilem_Flusser_1940.jpg.web.jpg",
    "type": "image",
    "title": "Vilem Flusser 1940.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/W1siZiIsIjUyNzA5MyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg",
    "type": "image",
    "title": "W1siZiIsIjUyNzA5MyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/W1siZiIsIjUyNzA5MyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.webp.web.jpg",
    "type": "image",
    "title": "W1siZiIsIjUyNzA5MyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.webp.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/WEB_2_Press_Performing_at_Boston_Symphony_Hall_1981._Photographer_s_name_unknown.jpg",
    "type": "image",
    "title": "WEB 2 Press Performing at Boston Symphony Hall 1981. Photographer s name unknown",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/WEB_2_Press_Performing_at_Boston_Symphony_Hall_1981._Photographer_s_name_unknown.webp.web.jpg",
    "type": "image",
    "title": "WEB 2 Press Performing at Boston Symphony Hall 1981. Photographer s name unknown.webp.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/burninglights.jpeg",
    "type": "image",
    "title": "burninglights",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/burninglights.jpeg.web.jpg",
    "type": "image",
    "title": "burninglights.jpeg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/collage.jpg",
    "type": "image",
    "title": "collage",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/collage.jpg.web.jpg",
    "type": "image",
    "title": "collage.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/henryrox.jpeg",
    "type": "image",
    "title": "henryrox",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/henryrox.jpeg.web.jpg",
    "type": "image",
    "title": "henryrox.jpeg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/petit_silence.jpeg",
    "type": "image",
    "title": "petit silence",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/petit_silence.jpeg.web.jpg",
    "type": "image",
    "title": "petit silence.jpeg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/taipeistory.jpg",
    "type": "image",
    "title": "taipeistory",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/taipeistory.jpg.web.jpg",
    "type": "image",
    "title": "taipeistory.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/valeska.jpg",
    "type": "image",
    "title": "valeska",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/valeska.jpg.web.jpg",
    "type": "image",
    "title": "valeska.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/wendy-carlos.jpeg",
    "type": "image",
    "title": "wendy carlos",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/wendy-carlos.jpeg.web.jpg",
    "type": "image",
    "title": "wendy carlos.jpeg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/wildatheart.jpg",
    "type": "image",
    "title": "wildatheart",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/wildatheart.jpg.web.jpg",
    "type": "image",
    "title": "wildatheart.jpg.web",
    "description": "",
    "href": ""
  },
  {
    "src": "img/source/pdf_previews/maya-deren-amateur-vs-professional.jpg",
    "type": "pdf",
    "title": "maya deren amateur vs professional",
    "description": "",
    "href": "img/source/maya-deren-amateur-vs-professional.pdf"
  }
];
