window.SOURCE_LAYOUT = [
  {
    "id": "petit-silence",
    "type": "image",
    "src": "img/source/petit_silence.jpeg",
    "text": "",
    "title": "les cahiers du silence",
    "description": "",
    "href": "",
    "left": "84.7227px",
    "top": "927.285px",
    "width": "154.086px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-note",
    "type": "concept",
    "src": "",
    "text": "source is not a bibliography",
    "title": "source is not a bibliography",
    "description": "it is just a collection of random stuff i saw on the internet",
    "href": "",
    "left": "39.3281px",
    "top": "40.2773px",
    "width": "235px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthbg1rd-czpmx",
    "type": "image",
    "src": "img/source/Jacqueline-Jong-Portrait-1960s.jpeg",
    "text": "",
    "title": "Jacqueline Jong Portrait 1960s",
    "description": "empecé viendo unos fanzines de jacqueline jong y aquí estoy.",
    "href": "",
    "left": "103.109px",
    "top": "157.43px",
    "width": "165.191px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthbg4k2-g97m2",
    "type": "image",
    "src": "img/source/burninglights.jpeg",
    "text": "",
    "title": "burninglights",
    "description": "",
    "href": "",
    "left": "144.879px",
    "top": "462.504px",
    "width": "220.539px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthc3swt-3s83n",
    "type": "image",
    "src": "img/source/_pdf_previews/maya-deren-amateur-vs-professional.jpg",
    "text": "",
    "title": "maya deren amateur vs professional",
    "description": "",
    "href": "",
    "left": "431.496px",
    "top": "100.684px",
    "width": "372.359px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthc3z1i-pe7v5",
    "type": "image",
    "src": "img/source/W1siZiIsIjUyNzA5MyJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MjAwMFx1MDAzZSJdXQ.jpg",
    "text": "",
    "title": "splitting",
    "description": "composición fotográfica de gordon matta-clark",
    "href": "",
    "left": "1018.48px",
    "top": "11.2656px",
    "width": "129.02px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthcg8z8-biorv",
    "type": "image",
    "src": "img/source/Vilem_Flusser_1940.jpg",
    "text": "",
    "title": "Vilem Flusser 1940",
    "description": "para más info:",
    "href": "https://archive.org/details/vilem-flusser-towards-a-philosophy-of-photography-ocr",
    "left": "1016.75px",
    "top": "1011.89px",
    "width": "103.277px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthcgcxc-shr82",
    "type": "image",
    "src": "img/source/1020878_w445_1500.jpeg",
    "text": "",
    "title": "henry rox",
    "description": "el otro día descubrí a este señor y bueno, qué maravilla.",
    "href": "",
    "left": "1008.29px",
    "top": "514.551px",
    "width": "182.617px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthcgjzr-xkamm",
    "type": "image",
    "src": "img/source/valeska.jpg",
    "text": "",
    "title": "valeska gert",
    "description": "pues resulta que la primera punki venía de berlín",
    "href": "",
    "left": "910.48px",
    "top": "304.883px",
    "width": "111.727px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthdk9ar-ra96k",
    "type": "image",
    "src": "img/source/WEB_2_Press_Performing_at_Boston_Symphony_Hall_1981._Photographer_s_name_unknown.jpg",
    "text": "",
    "title": "WEB 2 Press Performing at Boston Symphony Hall 1981. Photographer s name unknown",
    "description": "Fayrouz, o la voz más bonita del Líbano",
    "href": "",
    "left": "727.781px",
    "top": "827.027px",
    "width": "174.06px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  },
  {
    "id": "source-mthdkate-v1qvs",
    "type": "image",
    "src": "img/source/WEB_2_Press_Performing_at_Boston_Symphony_Hall_1981._Photographer_s_name_unknown.jpg",
    "text": "",
    "title": "WEB 2 Press Performing at Boston Symphony Hall 1981. Photographer s name unknown",
    "description": "",
    "href": "",
    "left": "446.258px",
    "top": "949.391px",
    "width": "275.673px",
    "transform": "rotate(0deg)",
    "zIndex": ""
  }
];\n